services:
  #Redis
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    #    command: redis-server --save 20 1 --loglevel warning
    command: redis-server --bind 0.0.0.0 --protected-mode no
    volumes:
      - cache:/data
    #    environment:
    #      - SPRING_DATA_REDIS_HOST=redis
    #      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - app-network
  #MongoDB
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  cache:
    driver: local