services:
  #Redis
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    #    command: redis-server --save 20 1 --loglevel warning
    command: redis-server --bind 0.0.0.0 --protected-mode no
    volumes:
      - cache:/data
    networks:
      - app-network
  #MongoDB
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network

  #Prometheus
  prometheus:
    image: prom/prometheus
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
  #Zipkin
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - app-network
  #Kafka
  kafka-1:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=WnLkTHhkQaiJbwP8FClPhw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://${HOSTNAME:-localhost}:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://kafka-1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - F:/Docker/Kafka/kafka-data/volume1:/bitnami/kafka
    networks:
      - app-network

  kafka-2:
    image: bitnami/kafka:latest
    ports:
    - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=WnLkTHhkQaiJbwP8FClPhw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9090,EXTERNAL://${HOSTNAME:-localhost}:9094
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9090,EXTERNAL://kafka-2:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - F:/Docker/Kafka/kafka-data/volume2:/bitnami/kafka
    networks:
      - app-network

  kafka-3:
    image: bitnami/kafka:latest
    ports:
      - "9096:9096"
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=WnLkTHhkQaiJbwP8FClPhw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9090,EXTERNAL://${HOSTNAME:-localhost}:9096
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9090,EXTERNAL://kafka-3:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - F:/Docker/Kafka/kafka-data/volume3:/bitnami/kafka
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9090,kafka-2:9090,kafka-3:9090
      # - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://localhost:8081 # Optional, if you have a schema registry
    networks:
      - app-network

#Eureka-Server
  eureka-server:
    image: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

#User-service
  user-service:
    image: user-service
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - mongo
      - redis
      - eureka-server
      - zipkin
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/database

#Product-service
  product-service:
    image: product-service
    build: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - mongo
      - eureka-server
      - zipkin
      - redis
      - kafka-1
      - kafka-2
      - kafka-3
      - kafka-ui
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/database
      - KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9094,kafka-3:9096
  #Order-service
  order-service:
    image: order-service
    build: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    networks:
      - app-network
    depends_on:
      - mongo
      - eureka-server
      - zipkin
      - redis
      - kafka-1
      - kafka-2
      - kafka-3
      - kafka-ui
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/database
      - KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9094,kafka-3:9096
#Notification-service
  notification-service:
    image: notification-service
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8084:8084"
    networks:
      - app-network
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - kafka-ui
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9094,kafka-3:9096
#Api-gateway
  api-gateway:
    image: api-gateway
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8181:8181"
    depends_on:
      - eureka-server
    environment:
      - FRONTEND_ALLOWED_ORIGINS=http://localhost:5173,http://frontend:5173
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  cache:
    driver: local