#spring:
#  cloud:
#    gateway:
#      global-cors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:5173"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#            allowedHeaders: "*"
#            allowCredentials: true